### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [f-montiel/comitiando#1]
Buen@s! como va? encontre tal como en el repositorio de front algunos comentarios que deberian ser eliminados

![image](https://user-images.githubusercontent.com/53904695/206606229-9be93e67-86d3-43c2-8804-5374bb6ad7dc.png)

Recordemos que si bien no alteran al funcionamiento, no estan vistos como buena practica.

Cualquier cosita pueden contactarme a [nicogonzalez2008@gmail.com](mailto:nicogonzalez2008@gmail.com) o por el slack de RollingCode

**Comment by f-montiel** [comment]
Elimine todos los comentarios

**Comment by eliseoe95** [comment]
Elimine todos los comentarios
