### ISSUE TITLE
Eliminar console.log

### ISSUE THREAD

**Issue by Nidev-lab** [f-montiel/comitiando#2]
Buenas!  encontre algunos console.log que no deberian estar..

![image](https://user-images.githubusercontent.com/53904695/206609869-f6e20930-5789-4379-a7c1-52aa6236f82c.png)

![image](https://user-images.githubusercontent.com/53904695/206607622-d09688cd-7a9f-4beb-8975-b2ba4e38a30e.png)

Por favor eliminar todos los console.log de la aplicacion.

 los console.log en los catch o en donde necesitemos mostrar un error a los usuario por consola, deberian ser console.error

Cualquier cosita pueden contactarme a [nicogonzalez2008@gmail.com](mailto:nicogonzalez2008@gmail.com) o por el slack de RollingCode

**Comment by f-montiel** [comment]
Elimine todos los console.log() menos el de la conexion a la base de datos (archivo database.js) y el del listen del puerto (archivo index.js).

**Comment by eliseoe95** [comment]
Elimine todos los console.log() menos el de la conexion a la base de datos (archivo database.js) y el del listen del puerto (archivo index.js).
